package com.roleManagement.rolebasedManagement.role;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.roleManagement.rolebasedManagement.configrolepermission.Configrolepermission;
import com.roleManagement.rolebasedManagement.permission.Permission;
import javax.management.relation.RoleList;
import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "role")
public class Role {
    @Id
    @Column(name = "role_id", nullable = false)
    public Integer id;

    @Column(name = "role_name", nullable = false, length = 50)
    public String roleName;

//code generated by jpa buddy


//    @ManyToOne(fetch = FetchType.LAZY, optional = false)
//    @JoinColumn(name = "permission_id", nullable = false)
//    private Permission permission;
//
//    @ManyToOne(fetch = FetchType.LAZY, optional = false)
//    @JoinColumn(name = "configrolepermission_id", nullable = false)
//    private Configrolepermission configrolepermission;
//
//    public Configrolepermission getConfigrolepermission() {
//        return configrolepermission;
//    }
//
//    public void setConfigrolepermission(Configrolepermission configrolepermission) {
//        this.configrolepermission = configrolepermission;
//    }
//    public Permission getPermission() {
//        return permission;
//    }
//
//    public void setPermission(Permission permission) {
//        this.permission = permission;
//    }

    //    code by me

    public Set<Permission> getPermission() {
        return permission;
    }

    public void setPermission(Set<Permission> permission) {
        this.permission = permission;
    }

    @ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="configrolepermission",
     joinColumns = @JoinColumn(name="role_id"),
            inverseJoinColumns = @JoinColumn(name="permission_id")
    )
    @JsonIgnore
    private Set<Permission>permission=new HashSet<>();

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

}